### ISSUE TITLE
IE 11 Site does not work

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/JuiceMarketplaceWebsite#102]
The JuiceMachineWebSite does not work with IE11. 

Site stay on "Loading" message.

**Comment by gomarcel** [comment]
[Uploading IE11_Aufruf bleibt auf loading.PNG...]

**Comment by bockha** [comment]
maybe just show a note, that the user shall download current software to access the marketplace

**Comment by MBeuttler** [comment]
IE11 is not supported. User will see a notification telling him to install a modern browser: Commit c971a960041805310268d9b17e31d714e8814f60
