### ISSUE TITLE
Design Database-Structure and Access-Model

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/JuiceMarketplaceWebsite#11]
- Which component (Core or Website) should access the database.
- Should we setup different databases for core and website
- Should we separate recipes / metadata / userdata with different datbases

**Comment by MBeuttler** [comment]
As discuessed: All data should be stored within the core application.

@goergch @gomarcel @bockha Can we close this issue?

**Comment by bockha** [comment]
In my opinion, there should be only one database which is located in the core. It should have different views (access rights) for different services like JuiceMarketplaceWebsite and JuiceMachineService.

**Comment by MBeuttler** [comment]
There is a different issue adressing the databse in the core: [](https://github.com/IUNO-TDM/MarketplaceCore/issues/8)

**Comment by MBeuttler** [comment]
Closing this ticket as the open questions are tracked by Issue 1 Issue 8
