### ISSUE TITLE
"TDM" picture on landing page with wrong spelling.

### ISSUE THREAD

**Issue by liefersfl** [IUNO-TDM/JuiceMarketplaceWebsite#113]
On the landing page, "Technologiedatenmarktplatz" is written as "Technologie Daten Markplatz" which is grammatically wrong. When separating the words to highlight the letters, the correct form would be "Technologie-Daten-Markplatz".

![broken image](https://iuno.axoom.cloud/assets/images/tdm_text.svg)

**Comment by bockha** [comment]
Mark**t**platz bitte auch immer mit kleinem t zwischen Mark und Platz.
