### ISSUE TITLE
dashboard for machines requesting recipe

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/JuiceMarketplaceWebsite#144]
Create a dashboard that shows a timeline with dots for each point in time a machine requested recipes from the market place. 

* [ ] extend JMS recipe route to save request in database
* [ ] add route to provide data for scatter plot
* [ ] add scatter plot graph to dashboards

Example:
![example](https://user-images.githubusercontent.com/24431070/38016583-bea322c2-326f-11e8-9484-04706367ba05.png)

**Comment by MBeuttler** [comment]
9c0b52017e1de36f6701bc95b02f4e056b785931
