### ISSUE TITLE
Upgrade @angular/flex-layout

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/JuiceMarketplaceWebsite#149]
- Update flex-layout to newer version
- Fix any layout issues

**Comment by MBeuttler** [comment]
Old: 
`<div fxLayout="row" fxLayoutGap="10px" fxLayoutWrap>`
New:
`<div fxLayout="row true">`
Add layout gap with css margin:
`margin: 5px 10px;`

**Comment by liefersfl** [comment]
flex-layout is up to date.
I think replacing fxLayoutGap by a css margin is not possible and fxLayoutGap is still part of flex-layout. Why does this have to be replaced?

**Comment by MBeuttler** [comment]
fxLayoutGap was not available in the version of flex-layout during my tests. Maybe this was just a bug. If everything works with the updated version - I'm fine with that.
