### ISSUE TITLE
Add quotes and authors

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/JuiceMarketplaceWebsite#153]
Add a carousel or something similar to display the authors and their expertise or quotes.

**Comment by MBeuttler** [comment]
example:
[https://bootsnipp.com/snippets/featured/responsive-quote-carousel](https://bootsnipp.com/snippets/featured/responsive-quote-carousel)

**Comment by MBeuttler** [comment]
424794fda424d60d6d03d7d8818b6c43c2337c20
