### ISSUE TITLE
Impressum - Kontakt - Datenschutz - Cookies

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/JuiceMarketplaceWebsite#25]

**Comment by bockha** [comment]
* [ ] Imprint: adapt the [TRUMPF imprint](https://www.trumpf.com/de_DE/meta/impressum/)
* [X] Contact: fulfilled with imprint; a contact form is optional
* [ ] Data Privacy Statement: adapt the [TRUMPF data privacy statement](https://www.trumpf.com/de_DE/meta/datenschutz/)
* [X] Cookies: fulfilled by data privacy statement
* [ ] Copyright and Trademarks: adapt the [TRUMPF statement](https://www.trumpf.com/de_DE/meta/copyright-und-markenzeichen/)
* [ ] Terms and Conditions: 
  * [ ] provide suggestion
  * [ ] discuss with legal department
