### ISSUE TITLE
Certificate Issue on Google Browser

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/JuiceMarketplaceWebsite#42]
Google Browser marks [website ](https://iuno.axoom.cloud/) as "not secure" because of a certificate issue.

**Comment by bockha** [comment]
![iuno-certificate](https://user-images.githubusercontent.com/24431070/29703355-7846fca2-8975-11e7-9753-4d3d7a9fcdec.png)

**Comment by goergch** [comment]
Certificate was reissued with certificate transparency
